M48
; DRILL file {KiCad 9.0.0} date 2025-03-20T11:59:10+0530
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2025-03-20T11:59:10+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X197000Y-80000
T2
X122460Y-92400
X131460Y-92400
X139910Y-92400
X148910Y-92400
M30
